In [ ]:
# Taller 01 - Pandas 
## Analisis del dataset Titanic.
### Objetivo: Aplicar la libreria Pandas para realizar procesos de expliracdión, limpieza, transformación y análisis de datos.
### Preguntas de análisis
# 1. ¿La tasa de supervivencia fue diferente entre hombre y mujeres?
# 2. ¿La clase del pasajero influyó en la supervivencia y en la tarifa pagada?
# 3. ¿Los menores de edad tuvieron una supervivencia diferente a la de los adultos?

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Exploración inicial del daraset.

In [8]:
df.shape

(891, 12)

In [ ]:
# El dataset contiene 891 filas y 12 columnas, por lo que cuenta con suficiente información para realizar un analisis básico.

In [10]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [12]:
df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [13]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# Apartir de la exloración inicial evidencimos que las columnas "Age","Cabin" y "Embarked", contienen valores nulos. Por esta razón, antes del análisis es necesario realizar limpieza de datps

In [ ]:
# 2. Limpieza de datos: Se realiza limpieza del dataset para tratar valores faltantes y tener la base lista para el análisis

In [14]:
# Eliminar filas duplicadas en caso que existan

df = df.drop_duplicates()

In [15]:
# Llenar edades vacías con el promedio.

df["Age"] = df["Age"].fillna(df["Age"].mean())

In [16]:
# Rellenar valores faltantes de Embarked con el valor mas frecuente.

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [17]:
# Eliminar la columna "Cabin" por que tiene demasiados nullos

df = df.drop(columns=["Cabin"])

In [18]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
# 3. Transformación de datos: Se crean nuevas variables que facilitaran el analisis de los datos.

In [ ]:
# Se crea la columna "GrupoEdad", para clasificar a los pasajeros entre menores de edad y adultos.

df["GrupoEdad"] = df["Age"].apply(lambda x: "Menor de edad" if x < 18 else "Adulto")
print(df[["Age", "GrupoEdad"]].head())

    Age GrupoEdad
0  22.0    Adulto
1  38.0    Adulto
2  26.0    Adulto
3  35.0    Adulto
4  35.0    Adulto

In [ ]:
# 4. Preguntas.
# Pregunta 1: ¿La tasa de supervivencia fue diferente entre hombre y mujeres?

## Calcular la tasa promedio de supervivenvia por sexo.

df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [24]:
# Cuenta cuantos hombre y mujeres hay.

df.groupby("Sex")["PassengerId"].count()

Sex
female    314
male      577
Name: PassengerId, dtype: int64

In [25]:
# Uso de filtros.

mujeres_sobrevivieron = df[(df["Sex"] == "female") & (df["Survived"] == 1)].shape[0]
hombres_sobrevivieron = df[(df["Sex"] == "male") & (df["Survived"] == 1)].shape[0]

print("Mujeres que sobrevivieron", mujeres_sobrevivieron)
print("Hombres que sobrevivieron", hombres_sobrevivieron)

Mujeres que sobrevivieron 233
Hombres que sobrevivieron 109

In [ ]:
# Se puede evidenciar que la tasa de supervivencia fue mayor en mujeres que en hombres. Esto indica que el sexo estuvo fuerte mente relacionado con la probabilidad de sobrevivir.

In [ ]:
# Pregunta 2: ¿La clase del pasajero influyó en la supervivencia y en la tarifa pagada?

# Calcular la supervivencia promedio por clase.

df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [ ]:
# Calcular la tarifa promedio por clase.

df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [28]:
df.groupby("Pclass")[["Survived","Fare"]].mean()

        Survived       Fare
Pclass
1       0.629630  84.154687
2       0.472826  20.662183
3       0.242363  13.675550

In [29]:
# Uso de flitros

primera_clase = df[df["Pclass"] == 1].shape[0]
segunda_clase = df[df["Pclass"] == 2].shape[0]
tercera_clase = df[df["Pclass"] == 3].shape[0]

print("Pasajeros en primera clase:", primera_clase)
print("Pasajeros en segunda clase:", segunda_clase)
print("Pasajeros en tercera clase:", tercera_clase)

Pasajeros en primera clase: 216
Pasajeros en segunda clase: 184
Pasajeros en tercera clase: 491

In [ ]:
# Los resultados muestran que los pasajeros en primera clase tuvieron una mayo tasa de supervivencia y pagaron tarifas mas altas. Esto indica que la clase social y económica del pasajero influyó en sus posibilidades de sobrevivir.

In [30]:
# Pregunta 3: ¿Los menores de edad tuvieron una supervivencia diferente a la de los adultos? 

df.groupby("GrupoEdad")["Survived"].mean()

GrupoEdad
Adulto           0.361183
Menor de edad    0.539823
Name: Survived, dtype: float64

In [31]:
df["GrupoEdad"].value_counts()

GrupoEdad
Adulto           778
Menor de edad    113
Name: count, dtype: int64

In [32]:
menores = df[df["GrupoEdad"] == "Menor de edad"].shape[0]
adultos = df[df["GrupoEdad"] == "Adulto"].shape[0]

print("Menores de edad", menores)
print("Adultos", adultos)

Menores de edad 113
Adultos 778

In [ ]:
# Con esos resultados sí se puede afirmar que la edad influyó en la probabilidad de supervivencia. ya que los menores de edad tuvieron una tasa de de sobrevivencia 53% y los adultos una tada de 36%

In [33]:
# Resumen general del análisis.

df.groupby(["Sex", "Pclass"])["Survived"].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

In [ ]:
# Conclusiones

# 1. El dataset del Titanic permitió aplicar procesos de exploración, limpieza, transformación y análisis utilizando Pandas.
# 2. Se identificaron valores faltantes en algunas columnas, los cuales fueron tratados mediante imputación y eliminación.
# 3. Las mujeres presentaron una tasa de supervivencia considerablemente mayor que los hombres.
# 4. Los pasajeros de primera clase tuvieron una mayor probabilidad de sobrevivir y pagaron tarifas más altas.
# 5. La creación de la variable `GrupoEdad` permitió comparar la supervivencia entre menores de edad y adultos.
# 6. El uso de filtros, transformaciones y agrupaciones permitió responder las preguntas planteadas con base en los datos.