In [1]:
%pip install requests pandas ipykernel

Requirement already satisfied: requests in c:\users\ana maria lopez\appdata\local\programs\python\python313\lib\site-packages (2.34.2)
Requirement already satisfied: pandas in c:\users\ana maria lopez\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: ipykernel in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (7.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ana maria lopez\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ana maria lopez\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\ana maria lopez\appdata\local\programs\python\python313\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\ana maria lopez\appdata\local\programs\python\python313\lib\site-packages (from requests) (2026.5.20)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ana maria lopez\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ana maria lopez\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: comm>=0.1.1 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (9.12.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (26.0)
Requirement already satisfied: psutil>=5.7 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.6)
Requirement already satisfied: platformdirs>=2.5 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.4)
Requirement already satisfied: six>=1.5 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\ana maria lopez\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import requests
import pandas as pd

In [3]:
# Consulta a la API
url = "https://pokeapi.co/api/v2/pokemon?limit=10"
response = requests.get(url)

# Verificar respuesta
if response.status_code == 200:
    data = response.json()
    pokemons = data['results']
else:
    print("Error en la consulta:", response.status_code)

# Convertir a DataFrame
df = pd.DataFrame(pokemons)
df.head()

         name                                   url
0   bulbasaur  https://pokeapi.co/api/v2/pokemon/1/
1     ivysaur  https://pokeapi.co/api/v2/pokemon/2/
2    venusaur  https://pokeapi.co/api/v2/pokemon/3/
3  charmander  https://pokeapi.co/api/v2/pokemon/4/
4  charmeleon  https://pokeapi.co/api/v2/pokemon/5/

In [4]:
# Obtener detalles adicionales
details = []
for p in pokemons:
    r = requests.get(p['url'])
    if r.status_code == 200:
        info = r.json()
        details.append({
            'name': info['name'],
            'height': info['height'],
            'weight': info['weight'],
            'types': ', '.join([t['type']['name'] for t in info['types']])
        })

# Crear DataFrame final
df_final = pd.DataFrame(details)
df_final.head()

         name  height  weight          types
0   bulbasaur       7      69  grass, poison
1     ivysaur      10     130  grass, poison
2    venusaur      20    1000  grass, poison
3  charmander       6      85           fire
4  charmeleon      11     190           fire

In [5]:
df_final.to_csv('pokemon_dataset.csv', index=False)
print("Archivo CSV generado correctamente.")

Archivo CSV generado correctamente.